In [148]:
import torch.utils
import numpy as np

## Part 1

In [149]:
report = []
with open('day_03_input') as file:
    for line in file:
        report.append(line.rstrip('\n'))
report

['011010010110',
 '101110100110',
 '011011011110',
 '100011010001',
 '011011100111',
 '011000100101',
 '101101011001',
 '010001001001',
 '100010110111',
 '001110110101',
 '100111011001',
 '100110111011',
 '000000111101',
 '000000011101',
 '011101000011',
 '101101001111',
 '110101011101',
 '010100000100',
 '100111010001',
 '111110001000',
 '000110110110',
 '001001101101',
 '001110110111',
 '101110110101',
 '010001111000',
 '111101010111',
 '110011101110',
 '010111011100',
 '100101011111',
 '111011011011',
 '100110100111',
 '001000101010',
 '101000010000',
 '101010000111',
 '000100100101',
 '111111111101',
 '000100101010',
 '101000101000',
 '101010010111',
 '111011000010',
 '100101010110',
 '010011000101',
 '010010111011',
 '100101100000',
 '001011111000',
 '101011111011',
 '111110101100',
 '100011100110',
 '101011010001',
 '100010010110',
 '110000000101',
 '101111011000',
 '011110000000',
 '000100110010',
 '111110000011',
 '011000101010',
 '101011010011',
 '001000011111',
 '010001100101

In [150]:
ones = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
zeros = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
for number in report:
    for index, bit in enumerate(number):
        if bit == '0':
            zeros[index] += 1
        else:
            ones[index] += 1
ones

[483, 487, 485, 467, 513, 509, 492, 532, 508, 497, 490, 506]

In [151]:
zeros

[517, 513, 515, 533, 487, 491, 508, 468, 492, 503, 510, 494]

In [152]:
ones = np.array(ones)
zeros = np.array(zeros)
diff = ones - zeros
diff1 = zeros - ones
diff

array([-34, -26, -30, -66,  26,  18, -16,  64,  16,  -6, -20,  12])

In [153]:
diff[diff > 0] = 1
diff[diff < 0] = 0
diff1[diff1 > 0] = 1
diff1[diff1 < 0] = 0
diff

array([0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1])

In [154]:
diff1

array([1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [155]:
diff = ''.join(["".join(item) for item in diff.astype(str)])
diff1 = ''.join([",".join(item) for item in diff1.astype(str)])
diff

'000011011001'

In [156]:
int(diff, 2) * int(diff1, 2)

841526

## Part 2

In [157]:
backupReport = report

In [158]:
finalOxygenGenerator = ''
for i in range(len(report[0])):
    finalList = []
    ones = 0
    zeros = 0
    for number in report:
        if number[i] == '0':
            zeros += 1
        else:
            ones += 1
    if ones >= zeros:
        finalOxygenGenerator += '1'
    else:
        finalOxygenGenerator += '0'
    for number in report:
        if number[:i+1] == finalOxygenGenerator[:i+1]:
            finalList.append(number)
    if len(finalList) == 1:
        finalOxygenGenerator = finalList[0]
        break
    report = finalList


finalOxygenGenerator

'010010011001'

In [159]:
report = backupReport

In [160]:
finalScrubber = ''
for i in range(len(report[0])):
    finalList = []
    ones = 0
    zeros = 0
    for number in report:
        if number[i] == '0':
            zeros += 1
        else:
            ones += 1
    if ones < zeros:
        finalScrubber += '1'
    else:
        finalScrubber += '0'
    for number in report:
        if number[:i+1] == finalScrubber[:i+1]:
            finalList.append(number)
    if len(finalList) == 1:
        finalScrubber = finalList[0]
        break
    report = finalList

finalScrubber

'111111100110'

In [161]:
int(finalOxygenGenerator, 2) * int(finalScrubber, 2)

4790390