In [64]:
import numpy as np

In [65]:
numberList = []
with open('day_05_input.txt') as file:
    for line in file:
        if line != '\n':
            row = line.rstrip('\n').split(' -> ')
            row = [element.split(',') for element in row]
            numberList.append(row)

In [66]:
numberList

[[['414', '379'], ['827', '379']],
 [['683', '947'], ['183', '947']],
 [['156', '577'], ['480', '577']],
 [['939', '503'], ['939', '959']],
 [['388', '907'], ['388', '349']],
 [['73', '572'], ['539', '106']],
 [['530', '157'], ['530', '530']],
 [['959', '896'], ['123', '60']],
 [['416', '698'], ['475', '698']],
 [['856', '281'], ['856', '943']],
 [['658', '767'], ['806', '915']],
 [['774', '799'], ['252', '799']],
 [['763', '833'], ['763', '469']],
 [['66', '314'], ['359', '314']],
 [['47', '984'], ['974', '57']],
 [['377', '52'], ['377', '739']],
 [['168', '935'], ['767', '935']],
 [['536', '778'], ['354', '778']],
 [['222', '919'], ['961', '180']],
 [['31', '419'], ['31', '390']],
 [['475', '232'], ['317', '232']],
 [['989', '980'], ['989', '855']],
 [['825', '237'], ['627', '39']],
 [['318', '896'], ['413', '801']],
 [['208', '57'], ['888', '57']],
 [['403', '796'], ['104', '796']],
 [['923', '937'], ['169', '183']],
 [['590', '827'], ['903', '514']],
 [['846', '416'], ['715', '416'

In [67]:
first_array = np.zeros((1000,1000))

In [68]:
for pair in numberList:
    x1 = int(pair[0][0])
    y1 = int(pair[0][1])
    x2 = int(pair[1][0])
    y2 = int(pair[1][1])
    if x1 - x2 == 0:  ## The same x coord - vertical vector
        array_with_vector = np.zeros((1000,1000))
        if y1 > y2:
            for i in range(y2, y1+1):
                array_with_vector[i, x1] = 1
        else:
            for i in range(y1, y2+1):
                array_with_vector[i, x1] = 1
        first_array += array_with_vector

    elif y1 - y2 == 0:  ## The same y coord - horizontal vector
        array_with_vector = np.zeros((1000,1000))
        if x1 > x2:
            for i in range(x2, x1+1):
                array_with_vector[y1, i] = 1
        else:
            for i in range(x1, x2+1):
                array_with_vector[y1, i] = 1
        first_array += array_with_vector

In [69]:
first_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [70]:
count = 0
for row in first_array:
    for column in row:
        if column > 1:
            count += 1
count

6461

## Part 2

In [71]:
second_array = np.zeros((1000,1000))

In [72]:
for pair in numberList:
    array_with_vector = np.zeros((1000,1000))
    x1 = int(pair[0][0])
    y1 = int(pair[0][1])
    x2 = int(pair[1][0])
    y2 = int(pair[1][1])
    if x1 - x2 == 0:  ## The same x coord - vertical vector
        if y1 > y2:
            for i in range(y2, y1+1):
                array_with_vector[i, x1] = 1
        else:
            for i in range(y1, y2+1):
                array_with_vector[i, x1] = 1

    elif y1 - y2 == 0:  ## The same y coord - horizontal vector
        if x1 > x2:
            for i in range(x2, x1+1):
                array_with_vector[y1, i] = 1
        else:
            for i in range(x1, x2+1):
                array_with_vector[y1, i] = 1
    
    else: ## diagonal vector
        if x1 > x2:
            if y1 > y2:
                for i, j in zip(range(x2, x1+1), range(y2, y1+1)):
                    array_with_vector[j, i] = 1
            else:
                for i, j in zip(range(x2, x1+1), range(y2, y1-1, -1)):
                    array_with_vector[j, i] = 1

        else:
            if y1 > y2:
                for i, j in zip(range(x2, x1-1, -1), range(y2, y1+1)):
                    array_with_vector[j, i] = 1
            else:
                for i, j in zip(range(x1, x2+1), range(y1, y2+1)):
                    array_with_vector[j, i] = 1
    second_array += array_with_vector

In [73]:
count = 0
for row in second_array:
    for column in row:
        if column > 1:
            count += 1
count

18065

19507

In [74]:
test = np.zeros((5, 5))
test[2, 4] = 1
test

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [75]:
numberList = []
with open('day_05_test.txt') as file:
    for line in file:
        if line != '\n':
            row = line.rstrip('\n').split(' -> ')
            row = [element.split(',') for element in row]
            numberList.append(row)

In [76]:
second_array = np.zeros((10,10))

In [77]:
for pair in numberList:
    array_with_vector = np.zeros((10,10))
    x1 = int(pair[0][0])
    y1 = int(pair[0][1])
    x2 = int(pair[1][0])
    y2 = int(pair[1][1])
    if x1 - x2 == 0:  ## The same x coord - vertical vector
        if y1 > y2:
            for i in range(y2, y1+1):
                array_with_vector[i, x1] = 1
        else:
            for i in range(y1, y2+1):
                array_with_vector[i, x1] = 1

    elif y1 - y2 == 0:  ## The same y coord - horizontal vector
        if x1 > x2:
            for i in range(x2, x1+1):
                array_with_vector[y1, i] = 1
        else:
            for i in range(x1, x2+1):
                array_with_vector[y1, i] = 1
    
    else: ## diagonal vector
        if x1 > x2:
            if y1 > y2:
                for i, j in zip(range(x2, x1+1), range(y2, y1+1)):
                    array_with_vector[j, i] = 1
            else:
                for i, j in zip(range(x2, x1+1), range(y2, y1-1, -1)):
                    array_with_vector[j, i] = 1

        else:
            if y1 > y2:
                for i, j in zip(range(x2, x1-1, -1), range(y2, y1+1)):
                    array_with_vector[j, i] = 1
            else:
                for i, j in zip(range(x1, x2+1), range(y1, y2+1)):
                    array_with_vector[j, i] = 1
    second_array += array_with_vector

In [78]:
second_array

array([[1., 0., 1., 0., 0., 0., 0., 1., 1., 0.],
       [0., 1., 1., 1., 0., 0., 0., 2., 0., 0.],
       [0., 0., 2., 0., 1., 0., 1., 1., 1., 0.],
       [0., 0., 0., 1., 0., 2., 0., 2., 0., 0.],
       [0., 1., 1., 2., 3., 1., 3., 2., 1., 1.],
       [0., 0., 0., 1., 0., 2., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [2., 2., 2., 1., 1., 1., 0., 0., 0., 0.]])